config/routes.rb
Rails.application.routes.draw do
  get "static/one"
  get "static/two"
  get "static/three"
  get "static/four"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static#one"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def one
  end

  def two
  end

  def three
  end

  def four
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mini Profiler Test" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo="<%= @turbo %>">
    <nav>
      <p>With turbo enabled - Failing</p>
      <ul>
        <li><%= link_to "one", static_one_path %></li>
        <li><%= link_to "two", static_two_path %></li>
        <li><%= link_to "three", static_three_path %></li>
        <li><%= link_to "four", static_four_path %></li>
      </ul>
    </nav>

    <nav>
      <p>With turbo disabled - Working</p>
      <ul>
        <li><%= link_to "one", static_one_path, data: { turbo: false } %></li>
        <li><%= link_to "two", static_two_path, data: { turbo: false } %></li>
        <li><%= link_to "three", static_three_path, data: { turbo: false } %></li>
        <li><%= link_to "four", static_four_path, data: { turbo: false } %></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
  <% console %>
</html>